name: 'WarsCore'
version: '0.37.1'
main: hm.moe.pokkedoll.warscore.WarsCore
authors: [Emorard]
softdepend: [Vault]

commands:
  game:
    permission: pokkedoll.command.game
  invite:
    permission: pokkedoll.command.invite
  resourcepack:
    aliases: [rs]
    permission: pokkedoll.command.resourcepack
  stats:
    permission: pokkedoll.command.stats
  whelp:
    permission: pokkedoll.command.whelp
  tag:
    permission: pokkedoll.command.tag
  killsound:
    aliases: [ks]
    permission: pokkedoll.command.killsound
  killeffect:
    aliases: [ke]
    permission: pokkedoll.command.killeffect
  warscore:
    aliases: [wc, wars]
    permission: pokkedoll.command.warscore
  item:
    permission: pokkedoll.command.item
  upgrade:
    aliases: [upg]
    permission: pokkedoll.command.upgrade
  merchant:
    aliases: [mer]
    permission: pokkedoll.command.merchant
  spawn:
    permission: pokkedoll.command.spawn

permission:
  pokkedoll.command.game:
    default: true
  pokkedoll.command.invite:
    default: true
  pokkedoll.command.resourcepack:
    default: true
  pokkedoll.command.stats:
    default: true
  pokkedoll.command.spawn:
    default: true
  pokkedoll.command.warscore:
    default: false
  pokkedoll.command.item:
    default: false
  pokkedoll.command.upgrade:
    default: false
  pokkedoll.command.merchant:
    default: false
  pokkedoll.user:
    default: true
    children:
      pokkedoll.command.game: true
      pokkedoll.command.invite: true
      pokkedoll.command.stats: true
      pokkedoll.command.spawn: true
  pokkedoll.admin:
    default: op
    children:
      pokkedoll.command.item: true
      pokkedoll.command.upgrade: true
      pokkedoll.command.merchant: true
