name: 'WarsCore'
version: '3.0.0-Alpha'
api-version: '1.17'
main: hm.moe.pokkedoll.warscore.WarsCore
authors: [Emorard]
softdepend: [Vault, CrackShot, PokkeDollDB]
commands:
  game:
    permission: pokkedoll.command.game
  invite:
    permission: pokkedoll.command.invite
  resourcepack:
    aliases: [rs]
    permission: pokkedoll.command.resourcepack
  stats:
    permission: pokkedoll.command.stats
  whelp:
    permission: pokkedoll.command.whelp
  tag:
    permission: pokkedoll.command.tag
  warscore:
    aliases: [wc, wars]
    permission: pokkedoll.command.warscore
  item:
    permission: pokkedoll.command.item
  upgrade:
    aliases: [upg]
    permission: pokkedoll.command.upgrade
  merchant:
    aliases: [mer]
    permission: pokkedoll.command.merchant
  spawn:
    permission: pokkedoll.command.spawn
  wp:
    permission: pokkedoll.command.weapon
  shop:
    permission: pokkedoll.command.shop
  sndchecker:
    aliases: [sc]
    permission: sndchecker.use
  money:
    permission: pokkedoll.command.money
  continue:
    permission: pokkedoll.command.continue
  cse:
    permission: pokkedoll.command.cse
  vote:
    permission: pokkedoll.command.vp

permissions:
  pokkedoll.command.game:
    default: true
  pokkedoll.command.invite:
    default: true
  pokkedoll.command.resourcepack:
    default: true
  pokkedoll.command.stats:
    default: true
  pokkedoll.command.spawn:
    default: true
  pokkedoll.command.warscore:
    default: op
  pokkedoll.command.item:
    default: op
  pokkedoll.command.upgrade:
    default: op
  pokkedoll.command.merchant:
    default: op
  pokkedoll.command.shop:
    default: op
  pokkedoll.command.cse:
    default: op
  pokkedoll.command.weapon:
    default: true
  pokkedoll.command.money:
    default: true
  pokkedoll.command.continue:
    default: true
  pokkedoll.command.vp:
    default: true

  pokkedoll.user:
    default: true
    children:
      pokkedoll.command.game: true
      pokkedoll.command.invite: true
      pokkedoll.command.stats: true
      pokkedoll.command.spawn: true
      pokkedoll.command.weapon: true
      pokkedoll.command.money: true
      pokkedoll.command.continue: true
      pokkedoll.command.vp: true

  pokkedoll.admin:
    default: op
    children:
      pokkedoll.command.warscore: true
      pokkedoll.command.item: true
      pokkedoll.command.upgrade: true
      pokkedoll.command.merchant: true
      pokkedoll.command.cse: true
  sndchecker.use:
    default: op