name: 'WarsCore'
version: '0.21'
main: hm.moe.pokkedoll.warscore.WarsCore
authors: [Emorard]
softdepend: [Vault]

commands:
  game:
    permission: pokkedoll.command.game
  invite:
    permission: pokkedoll.command.invite
  resourcepack:
    aliases: [rs]
    permission: pokkedoll.command.resourcepack
  stats:
    permission: pokkedoll.command.stats
  whelp:
    permission: pokkedoll.command.whelp
  tag:
    permission: pokkedoll.command.tag
  killsound:
    aliases: [ks]
    permission: pokkedoll.command.killsound
  killeffect:
    aliases: [ke]
    permission: pokkedoll.command.killeffect

permission:
  pokkedoll.command.game:
    default: true
  pokkedoll.command.invite:
    default: true
  pokkedoll.command.resourcepack:
    default: true
  pokkedoll.command.stats:
    default: true
  pokkedoll.command.whelp:
    default: false

  pokkedoll.user:
    default: true
  pokkedoll.admin:
    default: op