name: 'WarsCore'
version: '1.11.6-SNAPSHOT'
api-version: '1.16'
main: hm.moe.pokkedoll.warscore.WarsCore
authors: [Emorard]
softdepend: [Vault]

commands:
  game:
    permission: pokkedoll.command.user
  invite:
    permission: pokkedoll.command.user
  stats:
    permission: pokkedoll.command.user
  whelp:
    permission: pokkedoll.command.user
  tag:
    permission: pokkedoll.command.user
  spawn:
    permission: pokkedoll.command.user
  wp:
    permission: pokkedoll.command.user
  money:
    permission: pokkedoll.command.user
  continue:
    permission: pokkedoll.command.user

  shop:
    permission: pokkedoll.command.admin
  upgrade:
    aliases: [upg]
    permission: pokkedoll.command.admin
  warscore:
    aliases: [wc, wars]
    permission: pokkedoll.command.admin
  item:
    permission: pokkedoll.command.admin
  sndchecker:
    aliases: [sc]
    permission: sndchecker.use

permissions:
  pokkedoll.user:
    default: true
  pokkedoll.admin:
    default: op
  sndchecker.use:
    default: op