name: 'WarsCore'
version: '0.13C'
main: hm.moe.pokkedoll.warscore.WarsCore
authors: [Emorard]
softdepend: [Vault]

commands:
  game:
    permission: pokkedoll.command.game
  invite:
    permission: pokkedoll.command.invite
  resourcepack:
    aliases: [rs]
    permission: pokkedoll.command.resourcepack

permission:
  pokkedoll.command.game:
    default: true
  pokkedoll.command.invite:
    default: true
  pokkedoll.command.resourcepack:
    default: true